networks:
  development:
    verify: False
  ganache:
    verify: False
  rinkeby:
    verify: False
    ethernaut: "0x732a57705Aa14Dc7aFFb7AedA9eab472695BC4cf"
    infura: ${RINKEBY_INFURA}
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: ../.env