networks:
  development:
    verify: False
  ganache:
    verify: False
  rinkeby:
    verify: False
    gatekeeper: "0xA4DA1db88eaCb1441ECeebB4C0a790f77744b1CC"
    infura: ${INFURA}
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: ../.env