networks:
  development:
    verify: False
  ganache:
    verify: False
  rinkeby:
    verify: False
    delegation: "0x4AF5E91CaAD86875B10a8926a2FeCe1348aAc7fe"
    infura: ${RINKEBY_INFURA}
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: ../.env