dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
networks:
  rinkeby:
    recovery: "0x62A41eD7c8a0f993867086B52cCC5b124Ae4336E"
    infura: ${RINKEBY_INFURA}
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: ../.env